/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlmoxarifadoRouteImport } from './routes/almoxarifado'
import { Route as AmbientesRouteImport } from './routes/ambientes'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EquipamentosRouteImport } from './routes/equipamentos'
import { Route as InstacenaRouteImport } from './routes/instacena'
import { Route as LembretesRouteImport } from './routes/lembretes'
import { Route as RhRouteImport } from './routes/rh'
import { Route as AlmoxarifadoIndexRouteImport } from './routes/almoxarifado/index'
import { Route as AlmoxarifadoAduboRouteImport } from './routes/almoxarifado/adubo'
import { Route as AlmoxarifadoAspersoresRouteImport } from './routes/almoxarifado/aspersores'
import { Route as AlmoxarifadoEstoqueRouteImport } from './routes/almoxarifado/estoque'
import { Route as AlmoxarifadoNotasFiscaisRouteImport } from './routes/almoxarifado/notas-fiscais'
import { Route as AlmoxarifadoPedidosRouteImport } from './routes/almoxarifado/pedidos'
import { Route as AlmoxarifadoRequisicaoRouteImport } from './routes/almoxarifado/requisicao'
import { Route as EquipamentosIndexRouteImport } from './routes/equipamentos/index'
import { Route as EquipamentosEntradaSaidaRouteImport } from './routes/equipamentos/entrada-saida'
import { Route as EquipamentosTodosRouteImport } from './routes/equipamentos/todos'
import { Route as EquipamentosVistoriaRouteImport } from './routes/equipamentos/vistoria'
import { Route as InstacenaIndexRouteImport } from './routes/instacena/index'
import { Route as InstacenaUsernameRouteImport } from './routes/instacena/$username'
import { Route as InstacenaExplorarRouteImport } from './routes/instacena/explorar'
import { Route as InstacenaPerfilRouteImport } from './routes/instacena/perfil'
import { Route as InstacenaPesquisaRouteImport } from './routes/instacena/pesquisa'
import { Route as InstacenaReelsRouteImport } from './routes/instacena/reels'
import { Route as RhIndexRouteImport } from './routes/rh/index'
import { Route as RhEfetivoRouteImport } from './routes/rh/efetivo'
import { Route as RhListaPresencaRouteImport } from './routes/rh/lista-presenca'
import { Route as RhRelatorioPresencaRouteImport } from './routes/rh/relatorio-presenca'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmoxarifadoRoute = AlmoxarifadoRouteImport.update({
  id: '/almoxarifado',
  path: '/almoxarifado',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbientesRoute = AmbientesRouteImport.update({
  id: '/ambientes',
  path: '/ambientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosRoute = EquipamentosRouteImport.update({
  id: '/equipamentos',
  path: '/equipamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const InstacenaRoute = InstacenaRouteImport.update({
  id: '/instacena',
  path: '/instacena',
  getParentRoute: () => rootRouteImport,
} as any)
const LembretesRoute = LembretesRouteImport.update({
  id: '/lembretes',
  path: '/lembretes',
  getParentRoute: () => rootRouteImport,
} as any)
const RhRoute = RhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmoxarifadoIndexRoute = AlmoxarifadoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AlmoxarifadoRoute,
} as any)
const AlmoxarifadoAduboRoute = AlmoxarifadoAduboRouteImport.update({
  id: '/adubo',
  path: '/adubo',
  getParentRoute: () => AlmoxarifadoRoute,
} as any)
const AlmoxarifadoAspersoresRoute = AlmoxarifadoAspersoresRouteImport.update({
  id: '/aspersores',
  path: '/aspersores',
  getParentRoute: () => AlmoxarifadoRoute,
} as any)
const AlmoxarifadoEstoqueRoute = AlmoxarifadoEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AlmoxarifadoRoute,
} as any)
const AlmoxarifadoNotasFiscaisRoute =
  AlmoxarifadoNotasFiscaisRouteImport.update({
    id: '/notas-fiscais',
    path: '/notas-fiscais',
    getParentRoute: () => AlmoxarifadoRoute,
  } as any)
const AlmoxarifadoPedidosRoute = AlmoxarifadoPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AlmoxarifadoRoute,
} as any)
const AlmoxarifadoRequisicaoRoute = AlmoxarifadoRequisicaoRouteImport.update({
  id: '/requisicao',
  path: '/requisicao',
  getParentRoute: () => AlmoxarifadoRoute,
} as any)
const EquipamentosIndexRoute = EquipamentosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EquipamentosRoute,
} as any)
const EquipamentosEntradaSaidaRoute =
  EquipamentosEntradaSaidaRouteImport.update({
    id: '/entrada-saida',
    path: '/entrada-saida',
    getParentRoute: () => EquipamentosRoute,
  } as any)
const EquipamentosTodosRoute = EquipamentosTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => EquipamentosRoute,
} as any)
const EquipamentosVistoriaRoute = EquipamentosVistoriaRouteImport.update({
  id: '/vistoria',
  path: '/vistoria',
  getParentRoute: () => EquipamentosRoute,
} as any)
const InstacenaIndexRoute = InstacenaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstacenaRoute,
} as any)
const InstacenaUsernameRoute = InstacenaUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => InstacenaRoute,
} as any)
const InstacenaExplorarRoute = InstacenaExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => InstacenaRoute,
} as any)
const InstacenaPerfilRoute = InstacenaPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => InstacenaRoute,
} as any)
const InstacenaPesquisaRoute = InstacenaPesquisaRouteImport.update({
  id: '/pesquisa',
  path: '/pesquisa',
  getParentRoute: () => InstacenaRoute,
} as any)
const InstacenaReelsRoute = InstacenaReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => InstacenaRoute,
} as any)
const RhIndexRoute = RhIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RhRoute,
} as any)
const RhEfetivoRoute = RhEfetivoRouteImport.update({
  id: '/efetivo',
  path: '/efetivo',
  getParentRoute: () => RhRoute,
} as any)
const RhListaPresencaRoute = RhListaPresencaRouteImport.update({
  id: '/lista-presenca',
  path: '/lista-presenca',
  getParentRoute: () => RhRoute,
} as any)
const RhRelatorioPresencaRoute = RhRelatorioPresencaRouteImport.update({
  id: '/relatorio-presenca',
  path: '/relatorio-presenca',
  getParentRoute: () => RhRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/almoxarifado': typeof AlmoxarifadoRouteWithChildren
  '/ambientes': typeof AmbientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/equipamentos': typeof EquipamentosRouteWithChildren
  '/instacena': typeof InstacenaRouteWithChildren
  '/lembretes': typeof LembretesRoute
  '/rh': typeof RhRouteWithChildren
  '/almoxarifado/adubo': typeof AlmoxarifadoAduboRoute
  '/almoxarifado/aspersores': typeof AlmoxarifadoAspersoresRoute
  '/almoxarifado/estoque': typeof AlmoxarifadoEstoqueRoute
  '/almoxarifado/notas-fiscais': typeof AlmoxarifadoNotasFiscaisRoute
  '/almoxarifado/pedidos': typeof AlmoxarifadoPedidosRoute
  '/almoxarifado/requisicao': typeof AlmoxarifadoRequisicaoRoute
  '/equipamentos/entrada-saida': typeof EquipamentosEntradaSaidaRoute
  '/equipamentos/todos': typeof EquipamentosTodosRoute
  '/equipamentos/vistoria': typeof EquipamentosVistoriaRoute
  '/instacena/$username': typeof InstacenaUsernameRoute
  '/instacena/explorar': typeof InstacenaExplorarRoute
  '/instacena/perfil': typeof InstacenaPerfilRoute
  '/instacena/pesquisa': typeof InstacenaPesquisaRoute
  '/instacena/reels': typeof InstacenaReelsRoute
  '/rh/efetivo': typeof RhEfetivoRoute
  '/rh/lista-presenca': typeof RhListaPresencaRoute
  '/rh/relatorio-presenca': typeof RhRelatorioPresencaRoute
  '/almoxarifado/': typeof AlmoxarifadoIndexRoute
  '/equipamentos/': typeof EquipamentosIndexRoute
  '/instacena/': typeof InstacenaIndexRoute
  '/rh/': typeof RhIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ambientes': typeof AmbientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/lembretes': typeof LembretesRoute
  '/almoxarifado/adubo': typeof AlmoxarifadoAduboRoute
  '/almoxarifado/aspersores': typeof AlmoxarifadoAspersoresRoute
  '/almoxarifado/estoque': typeof AlmoxarifadoEstoqueRoute
  '/almoxarifado/notas-fiscais': typeof AlmoxarifadoNotasFiscaisRoute
  '/almoxarifado/pedidos': typeof AlmoxarifadoPedidosRoute
  '/almoxarifado/requisicao': typeof AlmoxarifadoRequisicaoRoute
  '/equipamentos/entrada-saida': typeof EquipamentosEntradaSaidaRoute
  '/equipamentos/todos': typeof EquipamentosTodosRoute
  '/equipamentos/vistoria': typeof EquipamentosVistoriaRoute
  '/instacena/$username': typeof InstacenaUsernameRoute
  '/instacena/explorar': typeof InstacenaExplorarRoute
  '/instacena/perfil': typeof InstacenaPerfilRoute
  '/instacena/pesquisa': typeof InstacenaPesquisaRoute
  '/instacena/reels': typeof InstacenaReelsRoute
  '/rh/efetivo': typeof RhEfetivoRoute
  '/rh/lista-presenca': typeof RhListaPresencaRoute
  '/rh/relatorio-presenca': typeof RhRelatorioPresencaRoute
  '/almoxarifado': typeof AlmoxarifadoIndexRoute
  '/equipamentos': typeof EquipamentosIndexRoute
  '/instacena': typeof InstacenaIndexRoute
  '/rh': typeof RhIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/almoxarifado': typeof AlmoxarifadoRouteWithChildren
  '/ambientes': typeof AmbientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/equipamentos': typeof EquipamentosRouteWithChildren
  '/instacena': typeof InstacenaRouteWithChildren
  '/lembretes': typeof LembretesRoute
  '/rh': typeof RhRouteWithChildren
  '/almoxarifado/adubo': typeof AlmoxarifadoAduboRoute
  '/almoxarifado/aspersores': typeof AlmoxarifadoAspersoresRoute
  '/almoxarifado/estoque': typeof AlmoxarifadoEstoqueRoute
  '/almoxarifado/notas-fiscais': typeof AlmoxarifadoNotasFiscaisRoute
  '/almoxarifado/pedidos': typeof AlmoxarifadoPedidosRoute
  '/almoxarifado/requisicao': typeof AlmoxarifadoRequisicaoRoute
  '/equipamentos/entrada-saida': typeof EquipamentosEntradaSaidaRoute
  '/equipamentos/todos': typeof EquipamentosTodosRoute
  '/equipamentos/vistoria': typeof EquipamentosVistoriaRoute
  '/instacena/$username': typeof InstacenaUsernameRoute
  '/instacena/explorar': typeof InstacenaExplorarRoute
  '/instacena/perfil': typeof InstacenaPerfilRoute
  '/instacena/pesquisa': typeof InstacenaPesquisaRoute
  '/instacena/reels': typeof InstacenaReelsRoute
  '/rh/efetivo': typeof RhEfetivoRoute
  '/rh/lista-presenca': typeof RhListaPresencaRoute
  '/rh/relatorio-presenca': typeof RhRelatorioPresencaRoute
  '/almoxarifado/': typeof AlmoxarifadoIndexRoute
  '/equipamentos/': typeof EquipamentosIndexRoute
  '/instacena/': typeof InstacenaIndexRoute
  '/rh/': typeof RhIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/almoxarifado'
    | '/ambientes'
    | '/configuracoes'
    | '/dashboard'
    | '/equipamentos'
    | '/instacena'
    | '/lembretes'
    | '/rh'
    | '/almoxarifado/adubo'
    | '/almoxarifado/aspersores'
    | '/almoxarifado/estoque'
    | '/almoxarifado/notas-fiscais'
    | '/almoxarifado/pedidos'
    | '/almoxarifado/requisicao'
    | '/equipamentos/entrada-saida'
    | '/equipamentos/todos'
    | '/equipamentos/vistoria'
    | '/instacena/$username'
    | '/instacena/explorar'
    | '/instacena/perfil'
    | '/instacena/pesquisa'
    | '/instacena/reels'
    | '/rh/efetivo'
    | '/rh/lista-presenca'
    | '/rh/relatorio-presenca'
    | '/almoxarifado/'
    | '/equipamentos/'
    | '/instacena/'
    | '/rh/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ambientes'
    | '/configuracoes'
    | '/dashboard'
    | '/lembretes'
    | '/almoxarifado/adubo'
    | '/almoxarifado/aspersores'
    | '/almoxarifado/estoque'
    | '/almoxarifado/notas-fiscais'
    | '/almoxarifado/pedidos'
    | '/almoxarifado/requisicao'
    | '/equipamentos/entrada-saida'
    | '/equipamentos/todos'
    | '/equipamentos/vistoria'
    | '/instacena/$username'
    | '/instacena/explorar'
    | '/instacena/perfil'
    | '/instacena/pesquisa'
    | '/instacena/reels'
    | '/rh/efetivo'
    | '/rh/lista-presenca'
    | '/rh/relatorio-presenca'
    | '/almoxarifado'
    | '/equipamentos'
    | '/instacena'
    | '/rh'
  id:
    | '__root__'
    | '/'
    | '/almoxarifado'
    | '/ambientes'
    | '/configuracoes'
    | '/dashboard'
    | '/equipamentos'
    | '/instacena'
    | '/lembretes'
    | '/rh'
    | '/almoxarifado/adubo'
    | '/almoxarifado/aspersores'
    | '/almoxarifado/estoque'
    | '/almoxarifado/notas-fiscais'
    | '/almoxarifado/pedidos'
    | '/almoxarifado/requisicao'
    | '/equipamentos/entrada-saida'
    | '/equipamentos/todos'
    | '/equipamentos/vistoria'
    | '/instacena/$username'
    | '/instacena/explorar'
    | '/instacena/perfil'
    | '/instacena/pesquisa'
    | '/instacena/reels'
    | '/rh/efetivo'
    | '/rh/lista-presenca'
    | '/rh/relatorio-presenca'
    | '/almoxarifado/'
    | '/equipamentos/'
    | '/instacena/'
    | '/rh/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlmoxarifadoRoute: typeof AlmoxarifadoRouteWithChildren
  AmbientesRoute: typeof AmbientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  EquipamentosRoute: typeof EquipamentosRouteWithChildren
  InstacenaRoute: typeof InstacenaRouteWithChildren
  LembretesRoute: typeof LembretesRoute
  RhRoute: typeof RhRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almoxarifado': {
      id: '/almoxarifado'
      path: '/almoxarifado'
      fullPath: '/almoxarifado'
      preLoaderRoute: typeof AlmoxarifadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambientes': {
      id: '/ambientes'
      path: '/ambientes'
      fullPath: '/ambientes'
      preLoaderRoute: typeof AmbientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos': {
      id: '/equipamentos'
      path: '/equipamentos'
      fullPath: '/equipamentos'
      preLoaderRoute: typeof EquipamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instacena': {
      id: '/instacena'
      path: '/instacena'
      fullPath: '/instacena'
      preLoaderRoute: typeof InstacenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lembretes': {
      id: '/lembretes'
      path: '/lembretes'
      fullPath: '/lembretes'
      preLoaderRoute: typeof LembretesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh': {
      id: '/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof RhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almoxarifado/': {
      id: '/almoxarifado/'
      path: '/'
      fullPath: '/almoxarifado/'
      preLoaderRoute: typeof AlmoxarifadoIndexRouteImport
      parentRoute: typeof AlmoxarifadoRoute
    }
    '/almoxarifado/adubo': {
      id: '/almoxarifado/adubo'
      path: '/adubo'
      fullPath: '/almoxarifado/adubo'
      preLoaderRoute: typeof AlmoxarifadoAduboRouteImport
      parentRoute: typeof AlmoxarifadoRoute
    }
    '/almoxarifado/aspersores': {
      id: '/almoxarifado/aspersores'
      path: '/aspersores'
      fullPath: '/almoxarifado/aspersores'
      preLoaderRoute: typeof AlmoxarifadoAspersoresRouteImport
      parentRoute: typeof AlmoxarifadoRoute
    }
    '/almoxarifado/estoque': {
      id: '/almoxarifado/estoque'
      path: '/estoque'
      fullPath: '/almoxarifado/estoque'
      preLoaderRoute: typeof AlmoxarifadoEstoqueRouteImport
      parentRoute: typeof AlmoxarifadoRoute
    }
    '/almoxarifado/notas-fiscais': {
      id: '/almoxarifado/notas-fiscais'
      path: '/notas-fiscais'
      fullPath: '/almoxarifado/notas-fiscais'
      preLoaderRoute: typeof AlmoxarifadoNotasFiscaisRouteImport
      parentRoute: typeof AlmoxarifadoRoute
    }
    '/almoxarifado/pedidos': {
      id: '/almoxarifado/pedidos'
      path: '/pedidos'
      fullPath: '/almoxarifado/pedidos'
      preLoaderRoute: typeof AlmoxarifadoPedidosRouteImport
      parentRoute: typeof AlmoxarifadoRoute
    }
    '/almoxarifado/requisicao': {
      id: '/almoxarifado/requisicao'
      path: '/requisicao'
      fullPath: '/almoxarifado/requisicao'
      preLoaderRoute: typeof AlmoxarifadoRequisicaoRouteImport
      parentRoute: typeof AlmoxarifadoRoute
    }
    '/equipamentos/': {
      id: '/equipamentos/'
      path: '/'
      fullPath: '/equipamentos/'
      preLoaderRoute: typeof EquipamentosIndexRouteImport
      parentRoute: typeof EquipamentosRoute
    }
    '/equipamentos/entrada-saida': {
      id: '/equipamentos/entrada-saida'
      path: '/entrada-saida'
      fullPath: '/equipamentos/entrada-saida'
      preLoaderRoute: typeof EquipamentosEntradaSaidaRouteImport
      parentRoute: typeof EquipamentosRoute
    }
    '/equipamentos/todos': {
      id: '/equipamentos/todos'
      path: '/todos'
      fullPath: '/equipamentos/todos'
      preLoaderRoute: typeof EquipamentosTodosRouteImport
      parentRoute: typeof EquipamentosRoute
    }
    '/equipamentos/vistoria': {
      id: '/equipamentos/vistoria'
      path: '/vistoria'
      fullPath: '/equipamentos/vistoria'
      preLoaderRoute: typeof EquipamentosVistoriaRouteImport
      parentRoute: typeof EquipamentosRoute
    }
    '/instacena/': {
      id: '/instacena/'
      path: '/'
      fullPath: '/instacena/'
      preLoaderRoute: typeof InstacenaIndexRouteImport
      parentRoute: typeof InstacenaRoute
    }
    '/instacena/$username': {
      id: '/instacena/$username'
      path: '/$username'
      fullPath: '/instacena/$username'
      preLoaderRoute: typeof InstacenaUsernameRouteImport
      parentRoute: typeof InstacenaRoute
    }
    '/instacena/explorar': {
      id: '/instacena/explorar'
      path: '/explorar'
      fullPath: '/instacena/explorar'
      preLoaderRoute: typeof InstacenaExplorarRouteImport
      parentRoute: typeof InstacenaRoute
    }
    '/instacena/perfil': {
      id: '/instacena/perfil'
      path: '/perfil'
      fullPath: '/instacena/perfil'
      preLoaderRoute: typeof InstacenaPerfilRouteImport
      parentRoute: typeof InstacenaRoute
    }
    '/instacena/pesquisa': {
      id: '/instacena/pesquisa'
      path: '/pesquisa'
      fullPath: '/instacena/pesquisa'
      preLoaderRoute: typeof InstacenaPesquisaRouteImport
      parentRoute: typeof InstacenaRoute
    }
    '/instacena/reels': {
      id: '/instacena/reels'
      path: '/reels'
      fullPath: '/instacena/reels'
      preLoaderRoute: typeof InstacenaReelsRouteImport
      parentRoute: typeof InstacenaRoute
    }
    '/rh/': {
      id: '/rh/'
      path: '/'
      fullPath: '/rh/'
      preLoaderRoute: typeof RhIndexRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/efetivo': {
      id: '/rh/efetivo'
      path: '/efetivo'
      fullPath: '/rh/efetivo'
      preLoaderRoute: typeof RhEfetivoRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/lista-presenca': {
      id: '/rh/lista-presenca'
      path: '/lista-presenca'
      fullPath: '/rh/lista-presenca'
      preLoaderRoute: typeof RhListaPresencaRouteImport
      parentRoute: typeof RhRoute
    }
    '/rh/relatorio-presenca': {
      id: '/rh/relatorio-presenca'
      path: '/relatorio-presenca'
      fullPath: '/rh/relatorio-presenca'
      preLoaderRoute: typeof RhRelatorioPresencaRouteImport
      parentRoute: typeof RhRoute
    }
  }
}

interface AlmoxarifadoRouteChildren {
  AlmoxarifadoAduboRoute: typeof AlmoxarifadoAduboRoute
  AlmoxarifadoAspersoresRoute: typeof AlmoxarifadoAspersoresRoute
  AlmoxarifadoEstoqueRoute: typeof AlmoxarifadoEstoqueRoute
  AlmoxarifadoNotasFiscaisRoute: typeof AlmoxarifadoNotasFiscaisRoute
  AlmoxarifadoPedidosRoute: typeof AlmoxarifadoPedidosRoute
  AlmoxarifadoRequisicaoRoute: typeof AlmoxarifadoRequisicaoRoute
  AlmoxarifadoIndexRoute: typeof AlmoxarifadoIndexRoute
}

const AlmoxarifadoRouteChildren: AlmoxarifadoRouteChildren = {
  AlmoxarifadoAduboRoute: AlmoxarifadoAduboRoute,
  AlmoxarifadoAspersoresRoute: AlmoxarifadoAspersoresRoute,
  AlmoxarifadoEstoqueRoute: AlmoxarifadoEstoqueRoute,
  AlmoxarifadoNotasFiscaisRoute: AlmoxarifadoNotasFiscaisRoute,
  AlmoxarifadoPedidosRoute: AlmoxarifadoPedidosRoute,
  AlmoxarifadoRequisicaoRoute: AlmoxarifadoRequisicaoRoute,
  AlmoxarifadoIndexRoute: AlmoxarifadoIndexRoute,
}

const AlmoxarifadoRouteWithChildren = AlmoxarifadoRoute._addFileChildren(
  AlmoxarifadoRouteChildren,
)

interface EquipamentosRouteChildren {
  EquipamentosEntradaSaidaRoute: typeof EquipamentosEntradaSaidaRoute
  EquipamentosTodosRoute: typeof EquipamentosTodosRoute
  EquipamentosVistoriaRoute: typeof EquipamentosVistoriaRoute
  EquipamentosIndexRoute: typeof EquipamentosIndexRoute
}

const EquipamentosRouteChildren: EquipamentosRouteChildren = {
  EquipamentosEntradaSaidaRoute: EquipamentosEntradaSaidaRoute,
  EquipamentosTodosRoute: EquipamentosTodosRoute,
  EquipamentosVistoriaRoute: EquipamentosVistoriaRoute,
  EquipamentosIndexRoute: EquipamentosIndexRoute,
}

const EquipamentosRouteWithChildren = EquipamentosRoute._addFileChildren(
  EquipamentosRouteChildren,
)

interface InstacenaRouteChildren {
  InstacenaUsernameRoute: typeof InstacenaUsernameRoute
  InstacenaExplorarRoute: typeof InstacenaExplorarRoute
  InstacenaPerfilRoute: typeof InstacenaPerfilRoute
  InstacenaPesquisaRoute: typeof InstacenaPesquisaRoute
  InstacenaReelsRoute: typeof InstacenaReelsRoute
  InstacenaIndexRoute: typeof InstacenaIndexRoute
}

const InstacenaRouteChildren: InstacenaRouteChildren = {
  InstacenaUsernameRoute: InstacenaUsernameRoute,
  InstacenaExplorarRoute: InstacenaExplorarRoute,
  InstacenaPerfilRoute: InstacenaPerfilRoute,
  InstacenaPesquisaRoute: InstacenaPesquisaRoute,
  InstacenaReelsRoute: InstacenaReelsRoute,
  InstacenaIndexRoute: InstacenaIndexRoute,
}

const InstacenaRouteWithChildren = InstacenaRoute._addFileChildren(
  InstacenaRouteChildren,
)

interface RhRouteChildren {
  RhEfetivoRoute: typeof RhEfetivoRoute
  RhListaPresencaRoute: typeof RhListaPresencaRoute
  RhRelatorioPresencaRoute: typeof RhRelatorioPresencaRoute
  RhIndexRoute: typeof RhIndexRoute
}

const RhRouteChildren: RhRouteChildren = {
  RhEfetivoRoute: RhEfetivoRoute,
  RhListaPresencaRoute: RhListaPresencaRoute,
  RhRelatorioPresencaRoute: RhRelatorioPresencaRoute,
  RhIndexRoute: RhIndexRoute,
}

const RhRouteWithChildren = RhRoute._addFileChildren(RhRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlmoxarifadoRoute: AlmoxarifadoRouteWithChildren,
  AmbientesRoute: AmbientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  EquipamentosRoute: EquipamentosRouteWithChildren,
  InstacenaRoute: InstacenaRouteWithChildren,
  LembretesRoute: LembretesRoute,
  RhRoute: RhRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
