/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AmbientesRouteImport } from './routes/ambientes'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InstacenaRouteImport } from './routes/instacena'
import { Route as LembretesRouteImport } from './routes/lembretes'
import { Route as InstacenaIndexRouteImport } from './routes/instacena/index'
import { Route as InstacenaUsernameRouteImport } from './routes/instacena/$username'
import { Route as InstacenaExplorarRouteImport } from './routes/instacena/explorar'
import { Route as InstacenaPerfilRouteImport } from './routes/instacena/perfil'
import { Route as InstacenaPesquisaRouteImport } from './routes/instacena/pesquisa'
import { Route as InstacenaReelsRouteImport } from './routes/instacena/reels'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbientesRoute = AmbientesRouteImport.update({
  id: '/ambientes',
  path: '/ambientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InstacenaRoute = InstacenaRouteImport.update({
  id: '/instacena',
  path: '/instacena',
  getParentRoute: () => rootRouteImport,
} as any)
const LembretesRoute = LembretesRouteImport.update({
  id: '/lembretes',
  path: '/lembretes',
  getParentRoute: () => rootRouteImport,
} as any)
const InstacenaIndexRoute = InstacenaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstacenaRoute,
} as any)
const InstacenaUsernameRoute = InstacenaUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => InstacenaRoute,
} as any)
const InstacenaExplorarRoute = InstacenaExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => InstacenaRoute,
} as any)
const InstacenaPerfilRoute = InstacenaPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => InstacenaRoute,
} as any)
const InstacenaPesquisaRoute = InstacenaPesquisaRouteImport.update({
  id: '/pesquisa',
  path: '/pesquisa',
  getParentRoute: () => InstacenaRoute,
} as any)
const InstacenaReelsRoute = InstacenaReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => InstacenaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ambientes': typeof AmbientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/instacena': typeof InstacenaRouteWithChildren
  '/lembretes': typeof LembretesRoute
  '/instacena/$username': typeof InstacenaUsernameRoute
  '/instacena/explorar': typeof InstacenaExplorarRoute
  '/instacena/perfil': typeof InstacenaPerfilRoute
  '/instacena/pesquisa': typeof InstacenaPesquisaRoute
  '/instacena/reels': typeof InstacenaReelsRoute
  '/instacena/': typeof InstacenaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ambientes': typeof AmbientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/lembretes': typeof LembretesRoute
  '/instacena/$username': typeof InstacenaUsernameRoute
  '/instacena/explorar': typeof InstacenaExplorarRoute
  '/instacena/perfil': typeof InstacenaPerfilRoute
  '/instacena/pesquisa': typeof InstacenaPesquisaRoute
  '/instacena/reels': typeof InstacenaReelsRoute
  '/instacena': typeof InstacenaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ambientes': typeof AmbientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/instacena': typeof InstacenaRouteWithChildren
  '/lembretes': typeof LembretesRoute
  '/instacena/$username': typeof InstacenaUsernameRoute
  '/instacena/explorar': typeof InstacenaExplorarRoute
  '/instacena/perfil': typeof InstacenaPerfilRoute
  '/instacena/pesquisa': typeof InstacenaPesquisaRoute
  '/instacena/reels': typeof InstacenaReelsRoute
  '/instacena/': typeof InstacenaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ambientes'
    | '/configuracoes'
    | '/dashboard'
    | '/instacena'
    | '/lembretes'
    | '/instacena/$username'
    | '/instacena/explorar'
    | '/instacena/perfil'
    | '/instacena/pesquisa'
    | '/instacena/reels'
    | '/instacena/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ambientes'
    | '/configuracoes'
    | '/dashboard'
    | '/lembretes'
    | '/instacena/$username'
    | '/instacena/explorar'
    | '/instacena/perfil'
    | '/instacena/pesquisa'
    | '/instacena/reels'
    | '/instacena'
  id:
    | '__root__'
    | '/'
    | '/ambientes'
    | '/configuracoes'
    | '/dashboard'
    | '/instacena'
    | '/lembretes'
    | '/instacena/$username'
    | '/instacena/explorar'
    | '/instacena/perfil'
    | '/instacena/pesquisa'
    | '/instacena/reels'
    | '/instacena/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmbientesRoute: typeof AmbientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  InstacenaRoute: typeof InstacenaRouteWithChildren
  LembretesRoute: typeof LembretesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambientes': {
      id: '/ambientes'
      path: '/ambientes'
      fullPath: '/ambientes'
      preLoaderRoute: typeof AmbientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instacena': {
      id: '/instacena'
      path: '/instacena'
      fullPath: '/instacena'
      preLoaderRoute: typeof InstacenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lembretes': {
      id: '/lembretes'
      path: '/lembretes'
      fullPath: '/lembretes'
      preLoaderRoute: typeof LembretesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instacena/': {
      id: '/instacena/'
      path: '/'
      fullPath: '/instacena/'
      preLoaderRoute: typeof InstacenaIndexRouteImport
      parentRoute: typeof InstacenaRoute
    }
    '/instacena/$username': {
      id: '/instacena/$username'
      path: '/$username'
      fullPath: '/instacena/$username'
      preLoaderRoute: typeof InstacenaUsernameRouteImport
      parentRoute: typeof InstacenaRoute
    }
    '/instacena/explorar': {
      id: '/instacena/explorar'
      path: '/explorar'
      fullPath: '/instacena/explorar'
      preLoaderRoute: typeof InstacenaExplorarRouteImport
      parentRoute: typeof InstacenaRoute
    }
    '/instacena/perfil': {
      id: '/instacena/perfil'
      path: '/perfil'
      fullPath: '/instacena/perfil'
      preLoaderRoute: typeof InstacenaPerfilRouteImport
      parentRoute: typeof InstacenaRoute
    }
    '/instacena/pesquisa': {
      id: '/instacena/pesquisa'
      path: '/pesquisa'
      fullPath: '/instacena/pesquisa'
      preLoaderRoute: typeof InstacenaPesquisaRouteImport
      parentRoute: typeof InstacenaRoute
    }
    '/instacena/reels': {
      id: '/instacena/reels'
      path: '/reels'
      fullPath: '/instacena/reels'
      preLoaderRoute: typeof InstacenaReelsRouteImport
      parentRoute: typeof InstacenaRoute
    }
  }
}

interface InstacenaRouteChildren {
  InstacenaUsernameRoute: typeof InstacenaUsernameRoute
  InstacenaExplorarRoute: typeof InstacenaExplorarRoute
  InstacenaPerfilRoute: typeof InstacenaPerfilRoute
  InstacenaPesquisaRoute: typeof InstacenaPesquisaRoute
  InstacenaReelsRoute: typeof InstacenaReelsRoute
  InstacenaIndexRoute: typeof InstacenaIndexRoute
}

const InstacenaRouteChildren: InstacenaRouteChildren = {
  InstacenaUsernameRoute: InstacenaUsernameRoute,
  InstacenaExplorarRoute: InstacenaExplorarRoute,
  InstacenaPerfilRoute: InstacenaPerfilRoute,
  InstacenaPesquisaRoute: InstacenaPesquisaRoute,
  InstacenaReelsRoute: InstacenaReelsRoute,
  InstacenaIndexRoute: InstacenaIndexRoute,
}

const InstacenaRouteWithChildren = InstacenaRoute._addFileChildren(
  InstacenaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmbientesRoute: AmbientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  InstacenaRoute: InstacenaRouteWithChildren,
  LembretesRoute: LembretesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
